version: '3.8'

networks:
  net_conversao_dist:

services:
  conversao-distancia:
    image: deividfae/conversao-distancia:v1
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8081:5000
    networks:
      - net_conversao_dist